version: "3.3"
services:
  gatsby-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
     - .:/app
     - /app/node_modules